version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm run serve 0.0.0.0:8080
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
    ports:
      - 8080:8080
