version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /srv/app
    volumes:
      - ./app:/srv/app
      - /srv/app/node_modules
    stdin_open: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8080:8080
