secret_key: 'django-insecure-gfu=mf#!+0am+p$a4^3i=^tz*17f71tma7p!i$ildo36b5uw@&'

postgres:
  database: Storage
  user: JonyDB
  password: jonydb876
  host: db
  port: 5432


email:
  host: smtp.yandex.ru
  port: 465
  user: KostrovProductionServer
  password: aeoowbdfukhmqerb
