secret_key: 'django-insecure-gfu=mf#!+0am+p$a4^3i=^tz*17f71tma7p!i$ildo36b5uw@&'


postgres:
  database: storage
  user: jonydb
  password: jonydb876
  host: 80.249.145.16
  port: 5432


email:
  host: smtp.yandex.ru
  port: 465
  user: KostrovProductionServer
  password: aeoowbdfukhmqerb


admin:
  login: jony
  password: jony
  
  
channel:
  host: '5.53.124.177'
  
  
cors:
  host: 'http://5.53.124.177'
